apiVersion: spec.keptn.sh/0.2.2

kind: "Shipyard"

metadata:

  name: "test-shipyard"

spec:

  stages:

    - name: "test-automation"

      sequences:

      - name: "functionaltests"

        tasks:

        - name: "test"                  # your integration gets triggered here

          properties:

            teststrategy: "functional"

        - name: "evaluation"



      - name: "performancetests"

        tasks:

        - name: "test"                  # your integration gets triggered here

          properties:

            teststrategy: "performance"

        - name: "evaluation"


